# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import complexdata_pb2 as complexdata__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='user.proto',
  package='ten64chat.user',
  syntax='proto3',
  serialized_pb=_b('\n\nuser.proto\x12\x0eten64chat.user\x1a\x11\x63omplexdata.proto\"g\n\x04User\x12\"\n\x04uuid\x18\x01 \x01(\x0b\x32\x14.ten64chat.data.UUID\x12\x13\n\x0b\x64isplayName\x18\x02 \x01(\t\x12&\n\x06status\x18\x03 \x01(\x0e\x32\x16.ten64chat.user.Status\"^\n\x10UserStatusChange\x12\"\n\x04user\x18\x01 \x01(\x0b\x32\x14.ten64chat.user.User\x12&\n\x06status\x18\x02 \x01(\x0e\x32\x16.ten64chat.user.Status*L\n\x06Status\x12\x0b\n\x07OFFLINE\x10\x00\x12\x0b\n\x07\x42LOCKED\x10\x02\x12\x12\n\x0e\x44O_NOT_DISTURB\x10\x03\x12\x08\n\x04\x41WAY\x10\x04\x12\n\n\x06ONLINE\x10\x05\x62\x06proto3')
  ,
  dependencies=[complexdata__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='ten64chat.user.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFFLINE', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BLOCKED', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DO_NOT_DISTURB', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AWAY', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ONLINE', index=4, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=250,
  serialized_end=326,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
OFFLINE = 0
BLOCKED = 2
DO_NOT_DISTURB = 3
AWAY = 4
ONLINE = 5



_USER = _descriptor.Descriptor(
  name='User',
  full_name='ten64chat.user.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='ten64chat.user.User.uuid', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='displayName', full_name='ten64chat.user.User.displayName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='ten64chat.user.User.status', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=152,
)


_USERSTATUSCHANGE = _descriptor.Descriptor(
  name='UserStatusChange',
  full_name='ten64chat.user.UserStatusChange',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='ten64chat.user.UserStatusChange.user', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='ten64chat.user.UserStatusChange.status', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=248,
)

_USER.fields_by_name['uuid'].message_type = complexdata__pb2._UUID
_USER.fields_by_name['status'].enum_type = _STATUS
_USERSTATUSCHANGE.fields_by_name['user'].message_type = _USER
_USERSTATUSCHANGE.fields_by_name['status'].enum_type = _STATUS
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserStatusChange'] = _USERSTATUSCHANGE
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:ten64chat.user.User)
  ))
_sym_db.RegisterMessage(User)

UserStatusChange = _reflection.GeneratedProtocolMessageType('UserStatusChange', (_message.Message,), dict(
  DESCRIPTOR = _USERSTATUSCHANGE,
  __module__ = 'user_pb2'
  # @@protoc_insertion_point(class_scope:ten64chat.user.UserStatusChange)
  ))
_sym_db.RegisterMessage(UserStatusChange)


# @@protoc_insertion_point(module_scope)
